// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAilO8XVeV86WaNJ0FtJtROt8RSRrMOYYs',
    appId: '1:307742403783:web:227f13f383aaf40948a2e2',
    messagingSenderId: '307742403783',
    projectId: 'flutterlistin-28e3a',
    authDomain: 'flutterlistin-28e3a.firebaseapp.com',
    storageBucket: 'flutterlistin-28e3a.firebasestorage.app',
    measurementId: 'G-NV9D6MTFMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgD6k2IgaHF9CqcYfUWgub_rTyrfoLDRI',
    appId: '1:307742403783:android:0dd084d9bade5b9748a2e2',
    messagingSenderId: '307742403783',
    projectId: 'flutterlistin-28e3a',
    storageBucket: 'flutterlistin-28e3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOoUVZ8_so71Nb4FF2vFkNRhAEuDQKpLo',
    appId: '1:307742403783:ios:530f0deaa8e1d69848a2e2',
    messagingSenderId: '307742403783',
    projectId: 'flutterlistin-28e3a',
    storageBucket: 'flutterlistin-28e3a.firebasestorage.app',
    iosBundleId: 'lima.ricarth.flutterFirebaseStorage',
  );

}