name: Run Maestro Tests

on:
  pull_request:
    branches: [main]

jobs:
  maestro-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maestro
        run: brew install maestro

      - name: Start emulator (Android ou iOS)
        run: |
          # scripts para iniciar emulador e aguardar

      - name: Run Maestro Flows
        run: maestro test .maestro/*.yaml
