name: CI Maestro

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  maestro-tests:
    runs-on: macos-latest # ou ubuntu-latest, se for só Android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # Se precisar buildar o app (Android)
      - name: Build Android Debug APK
        run: ./gradlew assembleDebug
        working-directory: android

      # Inicia emulador Android (opcional, se não usar Maestro Cloud)
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_5
          script: echo "Emulador iniciado"

      - name: Run Maestro Tests
        run: maestro test .maestro --format junit --output results.xml

      # Publica relatórios JUnit no GitHub Actions
      - name: Upload Maestro Test Results
        uses: actions/upload-artifact@v3
        with:
          name: maestro-results
          path: results.xml
