name: Flutter CI with Maestro

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maestro-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Instalação do Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0' # coloque a versão do seu projeto
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug

      # Instalação do Maestro
      - name: Setup Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # Rodar os testes do Maestro
      - name: Run Maestro tests
        run: |
          maestro test test/flows/login.yaml
