name: Testes de UI com Maestro

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar o Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: Rodar os testes no Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_3
          # Adicionar 'accel: off' para desabilitar a aceleração de hardware
          accel: off
          script: |
            # Instalar o Maestro
            curl -Ls "https://install.maestro.mobile.dev" | bash

            # Compilar o APK de release
            flutter build apk --release

            # Rodar os testes do Maestro
            $HOME/.maestro/bin/maestro test test/flows/login.yaml