name: CI Maestro

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  maestro-tests:
    runs-on: ubuntu-latest # pode ser macos-latest também

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0' # coloque a versão que você usa no projeto

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Build Flutter APK
        run: flutter build apk --release

      - name: Run Maestro Tests
        run: maestro test .maestro \
          --app build/app/outputs/flutter-apk/app-release.apk \
          --format junit --output results.xml

      - name: Upload Maestro Test Results
        uses: actions/upload-artifact@v4
        with:
          name: maestro-results
          path: results.xml
