name: CI Maestro

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  maestro-tests:
    runs-on: ubuntu-latest
    env:
      MAESTRO_CLI_NO_ANALYTICS: 1

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configura Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      # 3️⃣ Instala dependências Flutter
      - name: Get Flutter dependencies
        run: flutter pub get

      # 4️⃣ Instala Maestro CLI
      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # 5️⃣ Configura o Android SDK e emulador
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: default
          arch: x86_64
          force-avd: true

      # 6️⃣ Inicia o emulador
      - name: Start Android Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82

      # 7️⃣ Build Flutter APK (Debug)
      - name: Build Flutter APK
        run: flutter build apk --debug

      # 8️⃣ Run Maestro Tests
      - name: Run Maestro Tests
        run: |
          maestro test test/flows/login.yaml --format junit --output results.xml

      # 9️⃣ Upload resultados
      - name: Upload Maestro Test Results
        uses: actions/upload-artifact@v4
        with:
          name: maestro-results
          path: results.xml
