name: Flutter + Maestro Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install Maestro
        run: curl -Ls "https://get.maestro.mobile.dev" | bash

      - name: Set Maestro Path
        run: echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          build-tools: 33.0.2

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Create google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > android/app/google-services.json

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Start Android Emulator
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_SDK_ROOT }}
        run: |
          echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64" --device "pixel"
          $ANDROID_SDK_ROOT/emulator/emulator -avd test -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82

      - name: Build release APK
        run: flutter build apk --release

      - name: Run Maestro tests
        run: maestro test build/app/outputs/flutter-apk/app-release.apk test/flows/
